#!/usr/bin/env bash

aws ecr get-login-password --region ap-southeast-1 | docker login -u AWS --password-stdin "https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.ap-southeast-1.amazonaws.com"
